var questionList = [
	['Captal of Afghanistan?','Kabul','Harare','Lusaka','Sana\'a'],
	['Captal of Albania?','Tirana','Baku','Harare','Lusaka'],
	['Captal of Algeria?','Algiers','Tirana','Nassau','Harare'],
	['Captal of Andorra?','Andorra la Vella','Algiers','Tirana','Canberra'],
	['Captal of Angola?','Luanda','Andorra la Vella','Algiers','Tirana'],
	['Captal of Antigua and Barbuda?','Saint John\'s','Luanda','Andorra la Vella','Algiers'],
	['Captal of Argentina?','Buenos Aires','Saint John\'s','Luanda','Andorra la Vella'],
	['Captal of Armenia?','Yerevan','Buenos Aires','Saint John\'s','Luanda'],
	['Captal of Australia?','Canberra','Yerevan','Buenos Aires','Saint John\'s'],
	['Captal of Austria?','Vienna','Canberra','Yerevan','Buenos Aires'],
	['Captal of Azerbaijan?','Baku','Vienna','Canberra','Yerevan'],
	['Captal of Bahamas?','Nassau','Baku','Vienna','Canberra'],
	['Captal of Bahrain?','Manama','Nassau','Baku','Vienna'],
	['Captal of Bangladesh?','Dhaka','Manama','Nassau','Baku'],
	['Captal of Barbados?','Bridgetown','Dhaka','Manama','Nassau'],
	['Captal of Belarus?','Minsk','Bridgetown','Dhaka','Manama'],
	['Captal of Belgium?','Brussels','Minsk','Bridgetown','Dhaka'],
	['Captal of Belize?','Belmopan','Brussels','Minsk','Bridgetown'],
	['Captal of Benin?','Porto Novo','Belmopan','Brussels','Minsk'],
	['Captal of Bhutan?','Thimphu','Porto Novo','Belmopan','Brussels'],
	['Captal of Bolivia?','La Paz','Thimphu','Porto Novo','Belmopan'],
	['Captal of Bosnia and Herzegovina?','Sarajevo','La Paz','Thimphu','Porto Novo'],
	['Captal of Botswana?','Gaborone','Sarajevo','La Paz','Thimphu'],
	['Captal of Brazil?','Brasilia','Gaborone','Sarajevo','La Paz'],
	['Captal of Brunei?','Bandar Seri Begawan','Brasilia','Gaborone','Sarajevo'],
	['Captal of Bulgaria?','Sofia','Bandar Seri Begawan','Brasilia','Gaborone'],
	['Captal of Burkina Faso?','Ouagadougou','Sofia','Bandar Seri Begawan','Brasilia'],
	['Captal of Burundi?','Gitega','Ouagadougou','Sofia','Bandar Seri Begawan'],
	['Captal of Cambodia?','Phnom Penh','Gitega','Ouagadougou','Sofia'],
	['Captal of Cameroon?','Yaounde','Phnom Penh','Gitega','Ouagadougou'],
	['Captal of Canada?','Ottawa','Yaounde','Phnom Penh','Gitega'],
	['Captal of Cape Verde?','Praia','Ottawa','Yaounde','Phnom Penh'],
	['Captal of Central African Republic?','Bangui','Praia','Ottawa','Yaounde'],
	['Captal of Chad?','N\'Djamena','Bangui','Praia','Ottawa'],
	['Captal of Chile?','Santiago','N\'Djamena','Bangui','Praia'],
	['Captal of China?','Beijing','Santiago','N\'Djamena','Bangui'],
	['Captal of Colombia?','Bogota','Beijing','Santiago','N\'Djamena'],
	['Captal of Comoros?','Moroni','Bogota','Beijing','Santiago'],
	['Captal of Congo, Democratic Republic of the?','Kinshasa','Moroni','Bogota','Beijing'],
	['Captal of Congo, Republic of the?','Brazzaville','Kinshasa','Moroni','Bogota'],
	['Captal of Costa Rica?','San Jose','Brazzaville','Kinshasa','Moroni'],
	['Captal of Ivory Coast?','Yamoussoukro','San Jose','Brazzaville','Kinshasa'],
	['Captal of Croatia?','Zagreb','Yamoussoukro','San Jose','Brazzaville'],
	['Captal of Cuba?','Havana','Zagreb','Yamoussoukro','San Jose'],
	['Captal of Cyprus?','Nicosia','Havana','Zagreb','Yamoussoukro'],
	['Captal of Czech Republic (Czechia)?','Prague','Nicosia','Havana','Zagreb'],
	['Captal of Denmark?','Copenhagen','Prague','Nicosia','Havana'],
	['Captal of Djibouti?','Djibouti','Copenhagen','Prague','Nicosia'],
	['Captal of Dominica?','Roseau','Djibouti','Copenhagen','Prague'],
	['Captal of Dominican Republic?','Santo Domingo','Roseau','Djibouti','Copenhagen'],
	['Captal of East Timor?','Dili','Santo Domingo','Roseau','Djibouti'],
	['Captal of Ecuador?','Quito','Dili','Santo Domingo','Roseau'],
	['Captal of Egypt?','Cairo','Quito','Dili','Santo Domingo'],
	['Captal of El Salvador?','San Salvador','Cairo','Quito','Dili'],
	['Captal of England?','London','San Salvador','Cairo','Quito'],
	['Captal of Equatorial Guinea?','Malabo','London','San Salvador','Cairo'],
	['Captal of Eritrea?','Asmara','Malabo','London','San Salvador'],
	['Captal of Estonia?','Tallinn','Asmara','Malabo','London'],
	['Captal of Swaziland?','Mbabana','Tallinn','Asmara','Malabo'],
	['Captal of Ethiopia?','Addis Ababa','Mbabana','Tallinn','Asmara'],
	['Captal of Federated States of Micronesia?','Palikir','Addis Ababa','Mbabana','Tallinn'],
	['Captal of Fiji?','Suva','Palikir','Addis Ababa','Mbabana'],
	['Captal of Finland?','Helsinki','Suva','Palikir','Addis Ababa'],
	['Captal of France?','Paris','Helsinki','Suva','Palikir'],
	['Captal of Gabon?','Libreville','Paris','Helsinki','Suva'],
	['Captal of Gambia?','Banjul','Libreville','Paris','Helsinki'],
	['Captal of Georgia?','Tbilisi','Banjul','Libreville','Paris'],
	['Captal of Germany?','Berlin','Tbilisi','Banjul','Libreville'],
	['Captal of Ghana?','Accra','Berlin','Tbilisi','Banjul'],
	['Captal of Greece?','Athens','Accra','Berlin','Tbilisi'],
	['Captal of Grenada?','Saint George\'s','Athens','Accra','Berlin'],
	['Captal of Guatemala?','Guatemala City','Saint George\'s','Athens','Accra'],
	['Captal of Guinea?','Conakry','Guatemala City','Saint George\'s','Athens'],
	['Captal of Guinea-Bissau?','Bissau','Conakry','Guatemala City','Saint George\'s'],
	['Captal of Guyana?','Georgetown','Bissau','Conakry','Guatemala City'],
	['Captal of Haiti?','Port au Prince','Georgetown','Bissau','Conakry'],
	['Captal of Honduras?','Tegucigalpa','Port au Prince','Georgetown','Bissau'],
	['Captal of Hungary?','Budapest','Tegucigalpa','Port au Prince','Georgetown'],
	['Captal of Iceland?','Reykjavik','Budapest','Tegucigalpa','Port au Prince'],
	['Captal of India?','New Delhi','Reykjavik','Budapest','Tegucigalpa'],
	['Captal of Indonesia?','Jakarta','New Delhi','Reykjavik','Budapest'],
	['Captal of Iran?','Tehran','Jakarta','New Delhi','Reykjavik'],
	['Captal of Iraq?','Baghdad','Tehran','Jakarta','New Delhi'],
	['Captal of Ireland?','Dublin','Baghdad','Tehran','Jakarta'],
	['Captal of Italy?','Rome','Dublin','Baghdad','Tehran'],
	['Captal of Jamaica?','Kingston','Rome','Dublin','Baghdad'],
	['Captal of Japan?','Tokyo','Kingston','Rome','Dublin'],
	['Captal of Jordan?','Amman','Tokyo','Kingston','Rome'],
	['Captal of Kazakhstan?','Astana','Amman','Tokyo','Kingston'],
	['Captal of Kenya?','Nairobi','Astana','Amman','Tokyo'],
	['Captal of Kiribati?','Tarawa Atoll','Nairobi','Astana','Amman'],
	['Captal of Kosovo?','Pristina','Tarawa Atoll','Nairobi','Astana'],
	['Captal of Kuwait?','Kuwait City','Pristina','Tarawa Atoll','Nairobi'],
	['Captal of Kyrgyzstan?','Bishkek','Kuwait City','Pristina','Tarawa Atoll'],
	['Captal of Laos?','Vientiane','Bishkek','Kuwait City','Pristina'],
	['Captal of Latvia?','Riga','Vientiane','Bishkek','Kuwait City'],
	['Captal of Lebanon?','Beirut','Riga','Vientiane','Bishkek'],
	['Captal of Lesotho?','Maseru','Beirut','Riga','Vientiane'],
	['Captal of Liberia?','Monrovia','Maseru','Beirut','Riga'],
	['Captal of Libya?','Tripoli','Monrovia','Maseru','Beirut'],
	['Captal of Liechtenstein?','Vaduz','Tripoli','Monrovia','Maseru'],
	['Captal of Lithuania?','Vilnius','Vaduz','Tripoli','Monrovia'],
	['Captal of Luxembourg?','Luxembourg','Vilnius','Vaduz','Tripoli'],
	['Captal of Madagascar?','Antananarivo','Luxembourg','Vilnius','Vaduz'],
	['Captal of Malawi?','Lilongwe','Antananarivo','Luxembourg','Vilnius'],
	['Captal of Malaysia?','Kuala Lumpur','Lilongwe','Antananarivo','Luxembourg'],
	['Captal of Maldives?','Male','Kuala Lumpur','Lilongwe','Antananarivo'],
	['Captal of Mali?','Bamako','Male','Kuala Lumpur','Lilongwe'],
	['Captal of Malta?','Valletta','Bamako','Male','Kuala Lumpur'],
	['Captal of Marshall Islands?','Majuro','Valletta','Bamako','Male'],
	['Captal of Mauritania?','Nouakchott','Majuro','Valletta','Bamako'],
	['Captal of Mauritius?','Port Louis','Nouakchott','Majuro','Valletta'],
	['Captal of Mexico?','Mexico City','Port Louis','Nouakchott','Majuro'],
	['Captal of Moldova?','Chisinau','Mexico City','Port Louis','Nouakchott'],
	['Captal of Monaco?','Monaco','Chisinau','Mexico City','Port Louis'],
	['Captal of Mongolia?','Ulaanbaatar','Monaco','Chisinau','Mexico City'],
	['Captal of Montenegro?','Podgorica','Ulaanbaatar','Monaco','Chisinau'],
	['Captal of Morocco?','Rabat','Podgorica','Ulaanbaatar','Monaco'],
	['Captal of Mozambique?','Maputo','Rabat','Podgorica','Ulaanbaatar'],
	['Captal of Myanmar?','Nay Pyi Taw','Maputo','Rabat','Podgorica'],
	['Captal of Namibia?','Windhoek','Nay Pyi Taw','Maputo','Rabat'],
	['Captal of Nauru?','No official capital','Windhoek','Nay Pyi Taw','Maputo'],
	['Captal of Nepal?','Kathmandu','No official capital','Windhoek','Nay Pyi Taw'],
	['Captal of Netherlands?','Amsterdam','Kathmandu','No official capital','Windhoek'],
	['Captal of New Zealand?','Wellington','Amsterdam','Kathmandu','No official capital'],
	['Captal of Nicaragua?','Managua','Wellington','Amsterdam','Kathmandu'],
	['Captal of Niger?','Niamey','Managua','Wellington','Amsterdam'],
	['Captal of Nigeria?','Abuja','Niamey','Managua','Wellington'],
	['Captal of North Korea?','Pyongyang','Abuja','Niamey','Managua'],
	['Captal of North Macedonia (Macedonia)?','Skopje','Pyongyang','Abuja','Niamey'],
	['Captal of Northern Ireland?','Belfast','Skopje','Pyongyang','Abuja'],
	['Captal of Norway?','Oslo','Belfast','Skopje','Pyongyang'],
	['Captal of Oman?','Muscat','Oslo','Belfast','Skopje'],
	['Captal of Pakistan?','Islamabad','Muscat','Oslo','Belfast'],
	['Captal of Palau?','Melekeok','Islamabad','Muscat','Oslo'],
	['Captal of Palestine?','Jerusalem','Melekeok','Islamabad','Muscat'],
	['Captal of Panama?','Panama City','Jerusalem','Melekeok','Islamabad'],
	['Captal of Papua New Guinea?','Port Moresby','Panama City','Jerusalem','Melekeok'],
	['Captal of Paraguay?','Asuncion','Port Moresby','Panama City','Jerusalem'],
	['Captal of Peru?','Lima','Asuncion','Port Moresby','Panama City'],
	['Captal of Philippines?','Manila','Lima','Asuncion','Port Moresby'],
	['Captal of Poland?','Warsaw','Manila','Lima','Asuncion'],
	['Captal of Portugal?','Lisbon','Warsaw','Manila','Lima'],
	['Captal of Qatar?','Doha','Lisbon','Warsaw','Manila'],
	['Captal of Romania?','Bucharest','Doha','Lisbon','Warsaw'],
	['Captal of Russia?','Moscow','Bucharest','Doha','Lisbon'],
	['Captal of Rwanda?','Kigali','Moscow','Bucharest','Doha'],
	['Captal of Saint Kitts and Nevis?','Basseterre','Kigali','Moscow','Bucharest'],
	['Captal of Saint Lucia?','Castries','Basseterre','Kigali','Moscow'],
	['Captal of Saint Vincent and the Grenadines?','Kingstown','Castries','Basseterre','Kigali'],
	['Captal of Samoa?','Apia','Kingstown','Castries','Basseterre'],
	['Captal of San Marino?','San Marino','Apia','Kingstown','Castries'],
	['Captal of Sao Tome and Principe?','Sao Tome','San Marino','Apia','Kingstown'],
	['Captal of Saudi Arabia?','Riyadh','Sao Tome','San Marino','Apia'],
	['Captal of Scotland?','Edinburgh','Riyadh','Sao Tome','San Marino'],
	['Captal of Senegal?','Dakar','Edinburgh','Riyadh','Sao Tome'],
	['Captal of Serbia?','Belgrade','Dakar','Edinburgh','Riyadh'],
	['Captal of Seychelles?','Victoria','Belgrade','Dakar','Edinburgh'],
	['Captal of Sierra Leone?','Freetown','Victoria','Belgrade','Dakar'],
	['Captal of Singapore?','Singapore','Freetown','Victoria','Belgrade'],
	['Captal of Slovakia?','Bratislava','Singapore','Freetown','Victoria'],
	['Captal of Slovenia?','Ljubljana','Bratislava','Singapore','Freetown'],
	['Captal of Solomon Islands?','Honiara','Ljubljana','Bratislava','Singapore'],
	['Captal of Somalia?','Mogadishu','Honiara','Ljubljana','Bratislava'],
	['Captal of South Africa?','Cape Town','Mogadishu','Honiara','Ljubljana'],
	['Captal of South Korea?','Seoul','Cape Town','Mogadishu','Honiara'],
	['Captal of South Sudan?','Juba','Seoul','Cape Town','Mogadishu'],
	['Captal of Spain?','Madrid','Juba','Seoul','Cape Town'],
	['Captal of Sudan?','Khartoum','Madrid','Juba','Seoul'],
	['Captal of Suriname?','Paramaribo','Khartoum','Madrid','Juba'],
	['Captal of Sweden?','Stockholm','Paramaribo','Khartoum','Madrid'],
	['Captal of Switzerland?','Bern','Stockholm','Paramaribo','Khartoum'],
	['Captal of Syria?','Damascus','Bern','Stockholm','Paramaribo'],
	['Captal of Taiwan?','Taipei','Damascus','Bern','Stockholm'],
	['Captal of Tajikistan?','Dushanbe','Taipei','Damascus','Bern'],
	['Captal of Tanzania?','Dodoma','Dushanbe','Taipei','Damascus'],
	['Captal of Thailand?','Bangkok','Dodoma','Dushanbe','Taipei'],
	['Captal of Togo?','Lome','Bangkok','Dodoma','Dushanbe'],
	['Captal of Tonga?','Nuku\'alofa','Lome','Bangkok','Dodoma'],
	['Captal of Trinidad and Tobago?','Port of Spain','Nuku\'alofa','Lome','Bangkok'],
	['Captal of Tunisia?','Tunis','Port of Spain','Nuku\'alofa','Lome'],
	['Captal of Turkey?','Ankara','Tunis','Port of Spain','Nuku\'alofa'],
	['Captal of Turkmenistan?','Ashgabat','Ankara','Tunis','Port of Spain'],
	['Captal of Tuvalu?','Funafuti','Ashgabat','Ankara','Tunis'],
	['Captal of Uganda?','Kampala','Funafuti','Ashgabat','Ankara'],
	['Captal of Ukraine?','Kyiv or Kiev','Kampala','Funafuti','Ashgabat'],
	['Captal of United Arab Emirates?','Abu Dhabi','Kyiv or Kiev','Kampala','Funafuti'],
	['Captal of United Kingdom?','London','Abu Dhabi','Kyiv or Kiev','Kampala'],
	['Captal of United States?','Washington D.C.','London','Abu Dhabi','Kyiv or Kiev'],
	['Captal of Uruguay?','Montevideo','Washington D.C.','London','Abu Dhabi'],
	['Captal of Uzbekistan?','Tashkent','Montevideo','Washington D.C.','London'],
	['Captal of Vanuatu?','Port Vila','Tashkent','Montevideo','Washington D.C.'],
	['Captal of Vatican City?','Vatican City','Port Vila','Tashkent','Montevideo'],
	['Captal of Venezuela?','Caracas','Vatican City','Port Vila','Tashkent'],
	['Captal of Vietnam?','Hanoi','Caracas','Vatican City','Port Vila'],
	['Captal of Wales?','Cardiff','Hanoi','Caracas','Vatican City'],
	['Captal of Yemen?','Sana\'a','Cardiff','Hanoi','Caracas'],
	['Captal of Zambia?','Lusaka','Sana\'a','Cardiff','Hanoi'],
	['Captal of Zimbabwe?','Harare','Lusaka','Sana\'a','Cardiff']
];